name: first-github-action
on: [push]
jobs:
  explore-first-github-workflow:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - run: npm install -g bats
        - run: bats -
